#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtk-doc
Version  : 1.24
Release  : 8
URL      : https://download.gnome.org/sources/gtk-doc/1.24/gtk-doc-1.24.tar.xz
Source0  : https://download.gnome.org/sources/gtk-doc/1.24/gtk-doc-1.24.tar.xz
Summary  : GTK+ DocBook Documentation Generator
Group    : Development/Tools
License  : GFDL-1.1 GPL-2.0
Requires: gtk-doc-bin
Requires: gtk-doc-data
BuildRequires : bc
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : itstool
BuildRequires : libxml2-dev
BuildRequires : libxml2-python
BuildRequires : libxslt-bin
BuildRequires : openjade-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : vim

%description
gtk-doc is a set of perl scripts that generate API reference documention in
DocBook format.  It can extract documentation from source code comments in a
manner similar to java-doc.  It is used to generate the documentation for
GLib, Gtk+, and GNOME.

%package bin
Summary: bin components for the gtk-doc package.
Group: Binaries
Requires: gtk-doc-data

%description bin
bin components for the gtk-doc package.


%package data
Summary: data components for the gtk-doc package.
Group: Data

%description data
data components for the gtk-doc package.


%package dev
Summary: dev components for the gtk-doc package.
Group: Development
Requires: gtk-doc-bin
Requires: gtk-doc-data

%description dev
dev components for the gtk-doc package.


%prep
%setup -q -n gtk-doc-1.24

%build
%configure --disable-static --with-xml-catalog=/usr/share/defaults/xml/catalog
make V=1  %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gtkdoc-check
/usr/bin/gtkdoc-depscan
/usr/bin/gtkdoc-fixxref
/usr/bin/gtkdoc-mkdb
/usr/bin/gtkdoc-mkhtml
/usr/bin/gtkdoc-mkman
/usr/bin/gtkdoc-mkpdf
/usr/bin/gtkdoc-mktmpl
/usr/bin/gtkdoc-rebase
/usr/bin/gtkdoc-scan
/usr/bin/gtkdoc-scangobj
/usr/bin/gtkdocize

%files data
%defattr(-,root,root,-)
/usr/share/gtk-doc/data/devhelp2.xsd
/usr/share/gtk-doc/data/devhelp2.xsl
/usr/share/gtk-doc/data/gtk-doc.dcl
/usr/share/gtk-doc/data/gtk-doc.dsl
/usr/share/gtk-doc/data/gtk-doc.flat.make
/usr/share/gtk-doc/data/gtk-doc.make
/usr/share/gtk-doc/data/gtk-doc.notmpl-flat.make
/usr/share/gtk-doc/data/gtk-doc.notmpl.make
/usr/share/gtk-doc/data/gtk-doc.xsl
/usr/share/gtk-doc/data/gtkdoc-common.pl
/usr/share/gtk-doc/data/home.png
/usr/share/gtk-doc/data/left-insensitive.png
/usr/share/gtk-doc/data/left.png
/usr/share/gtk-doc/data/right-insensitive.png
/usr/share/gtk-doc/data/right.png
/usr/share/gtk-doc/data/style.css
/usr/share/gtk-doc/data/up-insensitive.png
/usr/share/gtk-doc/data/up.png
/usr/share/gtk-doc/data/version-greater-or-equal.xsl
/usr/share/help/C/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/C/gtk-doc-manual/index.docbook
/usr/share/help/bn_IN/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/bn_IN/gtk-doc-manual/index.docbook
/usr/share/help/de/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/de/gtk-doc-manual/index.docbook
/usr/share/help/el/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/el/gtk-doc-manual/index.docbook
/usr/share/help/en_GB/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/en_GB/gtk-doc-manual/index.docbook
/usr/share/help/es/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/es/gtk-doc-manual/index.docbook
/usr/share/help/fr/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/fr/gtk-doc-manual/index.docbook
/usr/share/help/gl/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/gl/gtk-doc-manual/index.docbook
/usr/share/help/gu/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/gu/gtk-doc-manual/index.docbook
/usr/share/help/pt_BR/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/pt_BR/gtk-doc-manual/index.docbook
/usr/share/help/sl/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/sl/gtk-doc-manual/index.docbook
/usr/share/help/sv/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/sv/gtk-doc-manual/index.docbook
/usr/share/help/ta/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/ta/gtk-doc-manual/index.docbook
/usr/share/help/te/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/te/gtk-doc-manual/index.docbook
/usr/share/help/zh_CN/gtk-doc-manual/fdl-appendix.xml
/usr/share/help/zh_CN/gtk-doc-manual/index.docbook
/usr/share/sgml/gtk-doc/gtk-doc.cat

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4
