#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v4
# autospec commit: 1ab68ca
#
Name     : gtk-doc
Version  : 1.34.0
Release  : 49
URL      : https://download.gnome.org/sources/gtk-doc/1.34/gtk-doc-1.34.0.tar.xz
Source0  : https://download.gnome.org/sources/gtk-doc/1.34/gtk-doc-1.34.0.tar.xz
Summary  : API documentation generator
Group    : Development/Tools
License  : GFDL-1.1 GPL-2.0
Requires: gtk-doc-bin = %{version}-%{release}
Requires: gtk-doc-data = %{version}-%{release}
Requires: gtk-doc-license = %{version}-%{release}
Requires: libxslt
Requires: pypi(pygments)
Requires: pypi(six)
Requires: source-highlight
BuildRequires : buildreq-gnome
BuildRequires : docbook-utils
BuildRequires : docbook-xml
BuildRequires : libxml2-dev
BuildRequires : libxml2-python
BuildRequires : libxslt-bin
BuildRequires : openjade-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pypi(six)
BuildRequires : source-highlight
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: noversion.patch

%description
GTK-Doc - Documentation generator for C code
============================================

%package bin
Summary: bin components for the gtk-doc package.
Group: Binaries
Requires: gtk-doc-data = %{version}-%{release}
Requires: gtk-doc-license = %{version}-%{release}

%description bin
bin components for the gtk-doc package.


%package data
Summary: data components for the gtk-doc package.
Group: Data

%description data
data components for the gtk-doc package.


%package dev
Summary: dev components for the gtk-doc package.
Group: Development
Requires: gtk-doc-bin = %{version}-%{release}
Requires: gtk-doc-data = %{version}-%{release}
Provides: gtk-doc-devel = %{version}-%{release}
Requires: gtk-doc = %{version}-%{release}

%description dev
dev components for the gtk-doc package.


%package license
Summary: license components for the gtk-doc package.
Group: Default

%description license
license components for the gtk-doc package.


%prep
%setup -q -n gtk-doc-1.34.0
cd %{_builddir}/gtk-doc-1.34.0
%patch -P 1 -p1
pushd ..
cp -a gtk-doc-1.34.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709737246
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static --with-xml-catalog=/usr/share/defaults/xml/catalog PYTHON=/usr/bin/python3
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static --with-xml-catalog=/usr/share/defaults/xml/catalog PYTHON=/usr/bin/python3
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709737246
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gtk-doc
cp %{_builddir}/gtk-doc-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gtk-doc/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/gtk-doc-%{version}/COPYING-DOCS %{buildroot}/usr/share/package-licenses/gtk-doc/5e7b36dfb18c7b8002bb9c41f87b65d280abd2ae || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gtkdoc-check
/usr/bin/gtkdoc-depscan
/usr/bin/gtkdoc-fixxref
/usr/bin/gtkdoc-mkdb
/usr/bin/gtkdoc-mkhtml
/usr/bin/gtkdoc-mkhtml2
/usr/bin/gtkdoc-mkman
/usr/bin/gtkdoc-mkpdf
/usr/bin/gtkdoc-rebase
/usr/bin/gtkdoc-scan
/usr/bin/gtkdoc-scangobj
/usr/bin/gtkdocize

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*
/usr/share/gtk-doc/data/devhelp2.xsd
/usr/share/gtk-doc/data/devhelp2.xsl
/usr/share/gtk-doc/data/gtk-doc.flat.make
/usr/share/gtk-doc/data/gtk-doc.make
/usr/share/gtk-doc/data/gtk-doc.no-xslt-flat.make
/usr/share/gtk-doc/data/gtk-doc.no-xslt.make
/usr/share/gtk-doc/data/gtk-doc.xsl
/usr/share/gtk-doc/data/home.png
/usr/share/gtk-doc/data/left-insensitive.png
/usr/share/gtk-doc/data/left.png
/usr/share/gtk-doc/data/right-insensitive.png
/usr/share/gtk-doc/data/right.png
/usr/share/gtk-doc/data/style.css
/usr/share/gtk-doc/data/up-insensitive.png
/usr/share/gtk-doc/data/up.png
/usr/share/gtk-doc/data/version-greater-or-equal.xsl
/usr/share/gtk-doc/python/gtkdoc/__init__.py
/usr/share/gtk-doc/python/gtkdoc/check.py
/usr/share/gtk-doc/python/gtkdoc/common.py
/usr/share/gtk-doc/python/gtkdoc/config.py
/usr/share/gtk-doc/python/gtkdoc/config_data.py
/usr/share/gtk-doc/python/gtkdoc/fixxref.py
/usr/share/gtk-doc/python/gtkdoc/highlight.py
/usr/share/gtk-doc/python/gtkdoc/md_to_db.py
/usr/share/gtk-doc/python/gtkdoc/mkdb.py
/usr/share/gtk-doc/python/gtkdoc/mkhtml.py
/usr/share/gtk-doc/python/gtkdoc/mkhtml2.py
/usr/share/gtk-doc/python/gtkdoc/mkman.py
/usr/share/gtk-doc/python/gtkdoc/mkpdf.py
/usr/share/gtk-doc/python/gtkdoc/rebase.py
/usr/share/gtk-doc/python/gtkdoc/scan.py
/usr/share/gtk-doc/python/gtkdoc/scangobj.py

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/gtk-doc.pc
/usr/share/aclocal/*.m4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk-doc/5e7b36dfb18c7b8002bb9c41f87b65d280abd2ae
/usr/share/package-licenses/gtk-doc/dfac199a7539a404407098a2541b9482279f690d
